### ISSUE TITLE
Week6&7

### ISSUE THREAD

**Issue by Ultifeek** [Santibenson/js_carousel#1]

**Comment by Santibenson** [comment]
What’s the issue that you’re raising? Sent from Mail for Windows From: UltifeekSent: Monday, 7 November 2022 14:52To: Santibenson/js_carouselCc: SubscribedSubject: Re: [Santibenson/js_carousel] Week6&7 (Issue #1) Closed #1 as not planned.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
